### ISSUE TITLE
Remove groupname from searchbox before next groupname is pasted in.

### ISSUE THREAD

**Issue by joel2607** [ACM-VIT/WhatsApp-Automation#10]
Issue can be found in line #31 of auto.py.

FIll in the code there to erase the current groupname entered in the search box before pasting the next groupname.

**Comment by Divyansh-Gemini** [comment]
Search Box is not getting cleared by this way.
@joel2607 plz check whether I'm correct or not.

**Comment by joel2607** [comment]
Then you're free to make the necessary changes to make the searchbox get cleared, and add the pull request.

**Comment by Divyansh-Gemini** [comment]
ok
